// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/seckill/v1/seckill.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SeckillService_DoSeckill_FullMethodName    = "/seckill.v1.SeckillService/DoSeckill"
	SeckillService_GetStock_FullMethodName     = "/seckill.v1.SeckillService/GetStock"
)

// SeckillServiceClient is the client API for SeckillService service.
type SeckillServiceClient interface {
	// 执行秒杀
	DoSeckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error)
	// 查询库存（网关轮询 + 客户端查询共用）
	GetStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error)
}

type seckillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillServiceClient(cc grpc.ClientConnInterface) SeckillServiceClient {
	return &seckillServiceClient{cc}
}

func (c *seckillServiceClient) DoSeckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error) {
	cOpts := append([]grpc.CallOption{}, opts...)
	out := new(SeckillResponse)
	err := c.cc.Invoke(ctx, SeckillService_DoSeckill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) GetStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, SeckillService_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillServiceServer is the server API for SeckillService service.
type SeckillServiceServer interface {
	// 执行秒杀
	DoSeckill(context.Context, *SeckillRequest) (*SeckillResponse, error)
	// 查询库存（网关轮询 + 客户端查询共用）
	GetStock(context.Context, *StockRequest) (*StockResponse, error)
	mustEmbedUnimplementedSeckillServiceServer()
}

// UnimplementedSeckillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeckillServiceServer struct {
}

func (UnimplementedSeckillServiceServer) DoSeckill(context.Context, *SeckillRequest) (*SeckillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSeckill not implemented")
}
func (UnimplementedSeckillServiceServer) GetStock(context.Context, *StockRequest) (*StockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedSeckillServiceServer) mustEmbedUnimplementedSeckillServiceServer() {}

// UnsafeSeckillServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeSeckillServiceServer interface {
	mustEmbedUnimplementedSeckillServiceServer()
}

func RegisterSeckillServiceServer(s grpc.ServiceRegistrar, srv SeckillServiceServer) {
	s.RegisterService(&SeckillService_ServiceDesc, srv)
}

func _SeckillService_DoSeckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).DoSeckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_DoSeckill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).DoSeckill(ctx, req.(*SeckillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).GetStock(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeckillService_ServiceDesc is the grpc.ServiceDesc for SeckillService service.
var SeckillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.v1.SeckillService",
	HandlerType: (*SeckillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSeckill",
			Handler:    _SeckillService_DoSeckill_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _SeckillService_GetStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seckill/v1/seckill.proto",
}
