FROM python:3.11-slim

WORKDIR /app
COPY worker.py ./
COPY proto/worker.proto ./proto/

RUN pip install --no-cache-dir grpcio grpcio-tools
RUN python -m grpc_tools.protoc -I proto --python_out=. --grpc_python_out=. proto/worker.proto

EXPOSE 50052
CMD ["python", "worker.py"]
